version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: woven-db
    environment:
      - POSTGRES_DB=woven
      - POSTGRES_USER=woven
      - POSTGRES_PASSWORD=woven
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
